version: '3'

services:

  app:
    container_name: optimizer-cargo-service
    build: .
    command: runserver
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


