"""
Product Schema Module.

This module contains Pydantic models for product data validation
and serialization, including base, creation, and response schemas.
"""

from pydantic import BaseModel


class ProductBase(BaseModel):
    """
    Base model for product data.

    Contains common fields shared across all product schemas.

    Attributes:
        nome: Product name
        espaco: Space occupied by the product
        valor: Product value
    """

    nome: str
    espaco: float
    valor: float


class ProductCreate(ProductBase):
    """
    Model for creating a new product.

    Inherits from ProductBase. The ID is generated by the backend.
    """

    pass


class Product(ProductBase):
    """
    Complete product model including ID.

    Used to represent a product returned by the API.

    Attributes:
        id: Unique product identifier
    """

    id: str

    class Config:
        """
        Pydantic configuration to allow model creation from object attributes.

        This is crucial for Pydantic to read data from ORM (SQLAlchemy)
        instances.
        """

        from_attributes = True
